name: Pip

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - master

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        platform: [windows-latest, macos-13, ubuntu-latest]
        python-version: ["3.8", "3.11"]

    runs-on: ${{ matrix.platform }}

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true

    - uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies on Ubuntu
      if: runner.os == 'Linux'
      run: |
        sudo apt-get update
        sudo apt-get install libopencv-dev -y

    - name: Install dependencies on macOS
      if: runner.os == 'macOS'
      run: |
        brew update
        brew install opencv

    - name: Install dependencies on Windows
      if: runner.os == 'Windows'
      run: |
        choco install opencv -y

    - name: Add requirements
      run: python -m pip install --upgrade wheel setuptools

    - name: Install Python dependencies
      run: pip install -r requirements.txt

    - name: Build and install
      run: pip install --verbose .[test]

    - name: Test
      run: python -m pytest
